version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app:/app

  database:
    image: mysql:5.7
    container_name: shortener-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./mysql-data:/var/lib/mysql"