# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain,Application,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    App\Infrastructure\Repository\UrlShortened\DoctrineUrlShortenedRepository:
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'

    App\Application\UrlShortened\Create\CreateUrlShortened:
        arguments:
            - '@App\Infrastructure\Repository\UrlShortened\DoctrineUrlShortenedRepository'

    App\Infrastructure\Controller\UrlShortened\SymfonyCreateUrlShortened:
        arguments:
            - '@App\Application\UrlShortened\Create\CreateUrlShortened'

    App\Application\UrlShortened\Delete\DeleteUrlShortened:
        arguments:
            - '@App\Infrastructure\Repository\UrlShortened\DoctrineUrlShortenedRepository'

    App\Infrastructure\Controller\UrlShortened\SymfonyDeleteUrlShortened:
        arguments:
            - '@App\Application\UrlShortened\Delete\DeleteUrlShortened'
            -
    App\Infrastructure\Controller\UrlShortened\SymfonyRedirectUrlShortened:
        arguments:
            - '@App\Application\UrlShortened\Read\ReadUrlShortened'

    App\Application\UrlShortened\Read\ReadUrlShortened:
        arguments:
            - '@App\Infrastructure\Repository\UrlShortened\DoctrineUrlShortenedRepository'